version: "2"
linters:
  default: standard
  settings:
    staticcheck:
      # Default: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
      # Disabled QF1008 ("Omit embedded fields from selector expression"): using embedded fields is often more readable.
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-QF1008"]
  exclusions:
    paths:
    - ".*/zz_generated.*\\.go$"

formatters:
  enable:
  - gofumpt
  - goimports
  settings:
    goimports:
      local-prefixes:
      - github.com/piraeusdatastore/linstor-affinity-controller
  exclusions:
    paths:
    - ".*/zz_generated.*\\.go$"
